/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package views;

/**
 *
 * @author Sepp
 */
public class BoxElementContractDetailsContact extends javax.swing.JPanel {

    /**
     * Creates new form BoxElementContractDetailsStudent
     */
    public BoxElementContractDetailsContact() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jl_name = new javax.swing.JLabel();
        jl_telefon = new javax.swing.JLabel();
        jl_ansprechpartner_value = new javax.swing.JLabel();
        jl_telefon_value = new javax.swing.JLabel();
        jl_bemerkung = new javax.swing.JLabel();
        jtf_bemerkung = new javax.swing.JTextField();

        jl_name.setText("Name:");

        jl_telefon.setText("Telefon:");

        jl_ansprechpartner_value.setText("leer");

        jl_telefon_value.setText("leer");

        jl_bemerkung.setText("Bemerkung:");

        jtf_bemerkung.setEditable(false);
        jtf_bemerkung.setText("leer");
        jtf_bemerkung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_bemerkungActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_name)
                            .addComponent(jl_telefon))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jl_ansprechpartner_value)
                            .addComponent(jl_telefon_value, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_bemerkung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtf_bemerkung)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_name)
                    .addComponent(jl_ansprechpartner_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_telefon)
                    .addComponent(jl_telefon_value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jl_bemerkung)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jtf_bemerkung, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void jtf_bemerkungActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             


    // Variables declaration - do not modify                     
    private javax.swing.JLabel jl_ansprechpartner_value;
    private javax.swing.JLabel jl_bemerkung;
    private javax.swing.JLabel jl_name;
    private javax.swing.JLabel jl_telefon;
    private javax.swing.JLabel jl_telefon_value;
    private javax.swing.JTextField jtf_bemerkung;
    // End of variables declaration                   
}
